version: '3.9'

services:

  postgres:
    image: postgres:16.0
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=student_crm