name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4 # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # https://github.com/marketplace/actions/setup-java-jdk
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test and build with Gradle
        run: ./gradlew clean build